site_name: Wave Engine Documentation
site_description: Revolutionary AI cognition system based on wave mechanics
site_url: https://midatlanticai.github.io/atlandemo/

repo_name: midatlanticAI/atlandemo
repo_url: https://github.com/midatlanticAI/atlandemo

theme:
  name: material
  palette:
    primary: blue
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
  - Architecture:
    - Core Engine: architecture/core.md
    - Wave Mechanics: architecture/waves.md
    - Temporal Cognition: architecture/temporal.md
  - API Reference:
    - Wave Engine: api/wave_engine.md
    - Expert Modules: api/expert_modules.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Features: examples/advanced.md
  - Performance:
    - Benchmarks: performance/benchmarks.md
    - Optimization: performance/optimization.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - toc:
      permalink: true 