[package]
name = "wave_engine"
version = "0.1.0"
edition = "2021"
description = "Ultra-fast wave-based cognition engine"
authors = ["Wave Engine Team"]
license = "MIT"
readme = "README.md"

[dependencies]
# No external dependencies needed - pure Rust implementation 