name: Wave LogicBench CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run one-command benchmark (run.ps1)
        shell: pwsh
        run: |
          ./run.ps1

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: wave_logicbench_full_results
          path: wave_logicbench_full_results.json 