name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov mypy ruff
      - name: Lint with ruff
        run: ruff .
      - name: Type check with mypy (ignore missing imports)
        run: mypy --ignore-missing-imports src expert_modules tools
      - name: Run tests with coverage
        run: pytest --cov=src --cov=expert_modules --cov=tools --cov-report=xml --cov-fail-under=60
      - name: Upload coverage to actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml 